name: Test

on: [ pull_request ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:  
      - name: Test
        run: |
          echo $APP_SECRET
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
      
      - name: Get Secret
        run: echo "Hello World Secret Gets" 