name: Test

on: [ pull_request ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:  
      - name: Test
        run: |
          echo $APP_SECRET
          cat .env
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }} > .env